server:
  port: ${SERVER_PORT}

spring:
  jackson:
    date-format: dd/MM/yyyy
    time-zone: Asia/Jakarta
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Jakarta
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECERET}
  expiration: ${JWT_EXPIRATION}

openai:
  api:
    token: ${OPENAI_API_TOKEN}
    url: https://api.openai.com/v1

logging:
  level:
    com.kinapi: DEBUG
    root: INFO