server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    date-format: dd/MM/yyyy
    time-zone: Asia/Jakarta
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Jakarta
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
    username: postgres.fugwlttlplfwcmdfwrik
    password: ObubuM1QWBQSdEB6
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver

jwt:
  secret: "myVerySecureSecretKeyThatIsAtLeast32CharactersLongForHMACSHA256Algorithm"
  expiration: 86400000

openai:
  api:
    token: ganti-pake-key-masing-masing
    url: https://api.openai.com/v1

supabase:
  url: https://fugwlttlplfwcmdfwrik.supabase.co
  api-key: ganti-pake-key-masing-masing
  storage:
    bucket:
      user-profiles: user-profiles
      gallery-album: gallery-album

logging:
  level:
    com.kinapi: DEBUG
    root: INFO